/* tslint:disable */
/* eslint-disable */
/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/absence-days-api';
export * from './api/absence-reasons-api';
export * from './api/absences-api';
export * from './api/bank-details-api';
export * from './api/benefits-api';
export * from './api/employees-api';
export * from './api/entitlements-api';
export * from './api/hierarchy-api';
export * from './api/jobs-api';
export * from './api/public-holidays-api';

