/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AbsenceDaysApi,
  AbsenceReasonsApi,
  AbsencesApi,
  BankDetailsApi,
  BenefitsApi,
  EmployeesApi,
  EntitlementsApi,
  HierarchyApi,
  JobsApi,
  PublicHolidaysApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { IrisSoftwareGroupCascadeCustom } from "./client-custom";

export class IrisSoftwareGroupCascade extends IrisSoftwareGroupCascadeCustom {
  readonly absenceDays: AbsenceDaysApi;
  readonly absenceReasons: AbsenceReasonsApi;
  readonly absences: AbsencesApi;
  readonly bankDetails: BankDetailsApi;
  readonly benefits: BenefitsApi;
  readonly employees: EmployeesApi;
  readonly entitlements: EntitlementsApi;
  readonly hierarchy: HierarchyApi;
  readonly jobs: JobsApi;
  readonly publicHolidays: PublicHolidaysApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.absenceDays = new AbsenceDaysApi(configuration);
    this.absenceReasons = new AbsenceReasonsApi(configuration);
    this.absences = new AbsencesApi(configuration);
    this.bankDetails = new BankDetailsApi(configuration);
    this.benefits = new BenefitsApi(configuration);
    this.employees = new EmployeesApi(configuration);
    this.entitlements = new EntitlementsApi(configuration);
    this.hierarchy = new HierarchyApi(configuration);
    this.jobs = new JobsApi(configuration);
    this.publicHolidays = new PublicHolidaysApi(configuration);
  }

}
