/* tslint:disable */
/* eslint-disable */
/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AbsenceReasonModel } from '../models';
// @ts-ignore
import { AbsenceReasonQueryModel } from '../models';
// @ts-ignore
import { EmployeeAbsenceReasonModel } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AbsenceReasonsApi - axios parameter creator
 * @export
 */
export const AbsenceReasonsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets a single Absence Reason referenced by ID.
         * @param {string} id Absence Reason ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getById', 'id', id)
            const localVarPath = `/attendance/absencereasons/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencereasons/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a single Employee Absence Reason referenced by ID.
         * @param {string} id Absence Reason ID.
         * @param {string} employeeId Employee ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeById: async (id: string, employeeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getEmployeeById', 'id', id)
            // verify required parameter 'employeeId' is not null or undefined
            assertParamExists('getEmployeeById', 'employeeId', employeeId)
            const localVarPath = `/attendance/absencereasons/{id}/employees/{employeeId}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)))
                .replace(`{${"employeeId"}}`, encodeURIComponent(String(employeeId !== undefined ? employeeId : `-employeeId-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencereasons/{id}/employees/{employeeId}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a list of Absence Reasons
         * @param {number} [$top] Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
         * @param {number} [$skip] Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
         * @param {string} [$filter] Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
         * @param {Array<string>} [$select] Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
         * @param {string} [$orderby] Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
         * @param {boolean} [$count] Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async ($top?: number, $skip?: number, $filter?: string, $select?: Array<string>, $orderby?: string, $count?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/attendance/absencereasons`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)
            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($filter !== undefined) {
                localVarQueryParameter['$filter'] = $filter;
            }

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }

            if ($orderby !== undefined) {
                localVarQueryParameter['$orderby'] = $orderby;
            }

            if ($count !== undefined) {
                localVarQueryParameter['$count'] = $count;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencereasons',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AbsenceReasonsApi - functional programming interface
 * @export
 */
export const AbsenceReasonsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AbsenceReasonsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets a single Absence Reason referenced by ID.
         * @param {AbsenceReasonsApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(requestParameters: AbsenceReasonsApiGetByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceReasonModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a single Employee Absence Reason referenced by ID.
         * @param {AbsenceReasonsApiGetEmployeeByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEmployeeById(requestParameters: AbsenceReasonsApiGetEmployeeByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeeAbsenceReasonModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEmployeeById(requestParameters.id, requestParameters.employeeId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a list of Absence Reasons
         * @param {AbsenceReasonsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(requestParameters: AbsenceReasonsApiListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceReasonQueryModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(requestParameters.$top, requestParameters.$skip, requestParameters.$filter, requestParameters.$select, requestParameters.$orderby, requestParameters.$count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AbsenceReasonsApi - factory interface
 * @export
 */
export const AbsenceReasonsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AbsenceReasonsApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets a single Absence Reason referenced by ID.
         * @param {AbsenceReasonsApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: AbsenceReasonsApiGetByIdRequest, options?: AxiosRequestConfig): AxiosPromise<AbsenceReasonModel> {
            return localVarFp.getById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a single Employee Absence Reason referenced by ID.
         * @param {AbsenceReasonsApiGetEmployeeByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeById(requestParameters: AbsenceReasonsApiGetEmployeeByIdRequest, options?: AxiosRequestConfig): AxiosPromise<EmployeeAbsenceReasonModel> {
            return localVarFp.getEmployeeById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a list of Absence Reasons
         * @param {AbsenceReasonsApiListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(requestParameters: AbsenceReasonsApiListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<AbsenceReasonQueryModel> {
            return localVarFp.list(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getById operation in AbsenceReasonsApi.
 * @export
 * @interface AbsenceReasonsApiGetByIdRequest
 */
export type AbsenceReasonsApiGetByIdRequest = {
    
    /**
    * Absence Reason ID.
    * @type {string}
    * @memberof AbsenceReasonsApiGetById
    */
    readonly id: string
    
}

/**
 * Request parameters for getEmployeeById operation in AbsenceReasonsApi.
 * @export
 * @interface AbsenceReasonsApiGetEmployeeByIdRequest
 */
export type AbsenceReasonsApiGetEmployeeByIdRequest = {
    
    /**
    * Absence Reason ID.
    * @type {string}
    * @memberof AbsenceReasonsApiGetEmployeeById
    */
    readonly id: string
    
    /**
    * Employee ID.
    * @type {string}
    * @memberof AbsenceReasonsApiGetEmployeeById
    */
    readonly employeeId: string
    
}

/**
 * Request parameters for list operation in AbsenceReasonsApi.
 * @export
 * @interface AbsenceReasonsApiListRequest
 */
export type AbsenceReasonsApiListRequest = {
    
    /**
    * Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
    * @type {number}
    * @memberof AbsenceReasonsApiList
    */
    readonly $top?: number
    
    /**
    * Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
    * @type {number}
    * @memberof AbsenceReasonsApiList
    */
    readonly $skip?: number
    
    /**
    * Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
    * @type {string}
    * @memberof AbsenceReasonsApiList
    */
    readonly $filter?: string
    
    /**
    * Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
    * @type {Array<string>}
    * @memberof AbsenceReasonsApiList
    */
    readonly $select?: Array<string>
    
    /**
    * Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
    * @type {string}
    * @memberof AbsenceReasonsApiList
    */
    readonly $orderby?: string
    
    /**
    * Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
    * @type {boolean}
    * @memberof AbsenceReasonsApiList
    */
    readonly $count?: boolean
    
}

/**
 * AbsenceReasonsApiGenerated - object-oriented interface
 * @export
 * @class AbsenceReasonsApiGenerated
 * @extends {BaseAPI}
 */
export class AbsenceReasonsApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Gets a single Absence Reason referenced by ID.
     * @param {AbsenceReasonsApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceReasonsApiGenerated
     */
    public getById(requestParameters: AbsenceReasonsApiGetByIdRequest, options?: AxiosRequestConfig) {
        return AbsenceReasonsApiFp(this.configuration).getById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a single Employee Absence Reason referenced by ID.
     * @param {AbsenceReasonsApiGetEmployeeByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceReasonsApiGenerated
     */
    public getEmployeeById(requestParameters: AbsenceReasonsApiGetEmployeeByIdRequest, options?: AxiosRequestConfig) {
        return AbsenceReasonsApiFp(this.configuration).getEmployeeById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a list of Absence Reasons
     * @param {AbsenceReasonsApiListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceReasonsApiGenerated
     */
    public list(requestParameters: AbsenceReasonsApiListRequest = {}, options?: AxiosRequestConfig) {
        return AbsenceReasonsApiFp(this.configuration).list(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
