/* tslint:disable */
/* eslint-disable */
/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AbsenceModel } from '../models';
// @ts-ignore
import { AbsenceQueryModel } from '../models';
// @ts-ignore
import { CreateAbsenceCommand } from '../models';
// @ts-ignore
import { ProblemDetails } from '../models';
// @ts-ignore
import { UpdateAbsenceCommand } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AbsencesApi - axios parameter creator
 * @export
 */
export const AbsencesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Creates a new Absence.
         * @param {CreateAbsenceCommand} [createAbsenceCommand] New Absence.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewAbsence: async (createAbsenceCommand?: CreateAbsenceCommand, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/attendance/absences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true; version=1';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createAbsenceCommand,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absences',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createAbsenceCommand, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Delete an Absence referenced by ID.
         * @param {string} id The ID of the Absence to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteById: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteById', 'id', id)
            const localVarPath = `/attendance/absences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absences/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a single Absence referenced by ID.
         * @param {string} id Absence ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getById', 'id', id)
            const localVarPath = `/attendance/absences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absences/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a list of Absences.
         * @param {number} [$top] Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
         * @param {number} [$skip] Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
         * @param {string} [$filter] Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
         * @param {Array<string>} [$select] Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
         * @param {string} [$orderby] Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
         * @param {boolean} [$count] Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList: async ($top?: number, $skip?: number, $filter?: string, $select?: Array<string>, $orderby?: string, $count?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/attendance/absences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)
            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($filter !== undefined) {
                localVarQueryParameter['$filter'] = $filter;
            }

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }

            if ($orderby !== undefined) {
                localVarQueryParameter['$orderby'] = $orderby;
            }

            if ($count !== undefined) {
                localVarQueryParameter['$count'] = $count;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absences',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Update an Absence referenced by ID.
         * @param {string} id The ID of the Absence to update.
         * @param {UpdateAbsenceCommand} [updateAbsenceCommand] The new state of the Absence.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateById: async (id: string, updateAbsenceCommand?: UpdateAbsenceCommand, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateById', 'id', id)
            const localVarPath = `/attendance/absences/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true; version=1';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateAbsenceCommand,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absences/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateAbsenceCommand, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AbsencesApi - functional programming interface
 * @export
 */
export const AbsencesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AbsencesApiAxiosParamCreator(configuration)
    return {
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Creates a new Absence.
         * @param {AbsencesApiCreateNewAbsenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNewAbsence(requestParameters: AbsencesApiCreateNewAbsenceRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const createAbsenceCommand: CreateAbsenceCommand = {
                EmployeeId: requestParameters.EmployeeId,
                AbsenceReasonId: requestParameters.AbsenceReasonId,
                Narrative: requestParameters.Narrative,
                StartDate: requestParameters.StartDate,
                EndDate: requestParameters.EndDate
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNewAbsence(createAbsenceCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Delete an Absence referenced by ID.
         * @param {AbsencesApiDeleteByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteById(requestParameters: AbsencesApiDeleteByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteById(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a single Absence referenced by ID.
         * @param {AbsencesApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(requestParameters: AbsencesApiGetByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a list of Absences.
         * @param {AbsencesApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(requestParameters: AbsencesApiGetListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceQueryModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getList(requestParameters.$top, requestParameters.$skip, requestParameters.$filter, requestParameters.$select, requestParameters.$orderby, requestParameters.$count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Update an Absence referenced by ID.
         * @param {AbsencesApiUpdateByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateById(requestParameters: AbsencesApiUpdateByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const updateAbsenceCommand: UpdateAbsenceCommand = {
                Narrative: requestParameters.Narrative,
                StartDate: requestParameters.StartDate,
                EndDate: requestParameters.EndDate,
                Id: requestParameters.Id
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateById(requestParameters.id, updateAbsenceCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AbsencesApi - factory interface
 * @export
 */
export const AbsencesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AbsencesApiFp(configuration)
    return {
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Creates a new Absence.
         * @param {AbsencesApiCreateNewAbsenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNewAbsence(requestParameters: AbsencesApiCreateNewAbsenceRequest = {}, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.createNewAbsence(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Delete an Absence referenced by ID.
         * @param {AbsencesApiDeleteByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteById(requestParameters: AbsencesApiDeleteByIdRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a single Absence referenced by ID.
         * @param {AbsencesApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: AbsencesApiGetByIdRequest, options?: AxiosRequestConfig): AxiosPromise<AbsenceModel> {
            return localVarFp.getById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a list of Absences.
         * @param {AbsencesApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList(requestParameters: AbsencesApiGetListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<AbsenceQueryModel> {
            return localVarFp.getList(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Update an Absence referenced by ID.
         * @param {AbsencesApiUpdateByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateById(requestParameters: AbsencesApiUpdateByIdRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateById(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createNewAbsence operation in AbsencesApi.
 * @export
 * @interface AbsencesApiCreateNewAbsenceRequest
 */
export type AbsencesApiCreateNewAbsenceRequest = {
    
} & CreateAbsenceCommand

/**
 * Request parameters for deleteById operation in AbsencesApi.
 * @export
 * @interface AbsencesApiDeleteByIdRequest
 */
export type AbsencesApiDeleteByIdRequest = {
    
    /**
    * The ID of the Absence to delete.
    * @type {string}
    * @memberof AbsencesApiDeleteById
    */
    readonly id: string
    
}

/**
 * Request parameters for getById operation in AbsencesApi.
 * @export
 * @interface AbsencesApiGetByIdRequest
 */
export type AbsencesApiGetByIdRequest = {
    
    /**
    * Absence ID.
    * @type {string}
    * @memberof AbsencesApiGetById
    */
    readonly id: string
    
}

/**
 * Request parameters for getList operation in AbsencesApi.
 * @export
 * @interface AbsencesApiGetListRequest
 */
export type AbsencesApiGetListRequest = {
    
    /**
    * Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
    * @type {number}
    * @memberof AbsencesApiGetList
    */
    readonly $top?: number
    
    /**
    * Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
    * @type {number}
    * @memberof AbsencesApiGetList
    */
    readonly $skip?: number
    
    /**
    * Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
    * @type {string}
    * @memberof AbsencesApiGetList
    */
    readonly $filter?: string
    
    /**
    * Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
    * @type {Array<string>}
    * @memberof AbsencesApiGetList
    */
    readonly $select?: Array<string>
    
    /**
    * Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
    * @type {string}
    * @memberof AbsencesApiGetList
    */
    readonly $orderby?: string
    
    /**
    * Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
    * @type {boolean}
    * @memberof AbsencesApiGetList
    */
    readonly $count?: boolean
    
}

/**
 * Request parameters for updateById operation in AbsencesApi.
 * @export
 * @interface AbsencesApiUpdateByIdRequest
 */
export type AbsencesApiUpdateByIdRequest = {
    
    /**
    * The ID of the Absence to update.
    * @type {string}
    * @memberof AbsencesApiUpdateById
    */
    readonly id: string
    
} & UpdateAbsenceCommand

/**
 * AbsencesApiGenerated - object-oriented interface
 * @export
 * @class AbsencesApiGenerated
 * @extends {BaseAPI}
 */
export class AbsencesApiGenerated extends BaseAPI {
    /**
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
     * @summary Creates a new Absence.
     * @param {AbsencesApiCreateNewAbsenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsencesApiGenerated
     */
    public createNewAbsence(requestParameters: AbsencesApiCreateNewAbsenceRequest = {}, options?: AxiosRequestConfig) {
        return AbsencesApiFp(this.configuration).createNewAbsence(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
     * @summary Delete an Absence referenced by ID.
     * @param {AbsencesApiDeleteByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsencesApiGenerated
     */
    public deleteById(requestParameters: AbsencesApiDeleteByIdRequest, options?: AxiosRequestConfig) {
        return AbsencesApiFp(this.configuration).deleteById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a single Absence referenced by ID.
     * @param {AbsencesApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsencesApiGenerated
     */
    public getById(requestParameters: AbsencesApiGetByIdRequest, options?: AxiosRequestConfig) {
        return AbsencesApiFp(this.configuration).getById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a list of Absences.
     * @param {AbsencesApiGetListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsencesApiGenerated
     */
    public getList(requestParameters: AbsencesApiGetListRequest = {}, options?: AxiosRequestConfig) {
        return AbsencesApiFp(this.configuration).getList(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
     * @summary Update an Absence referenced by ID.
     * @param {AbsencesApiUpdateByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsencesApiGenerated
     */
    public updateById(requestParameters: AbsencesApiUpdateByIdRequest, options?: AxiosRequestConfig) {
        return AbsencesApiFp(this.configuration).updateById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
