/* tslint:disable */
/* eslint-disable */
/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AbsenceDayModel } from '../models';
// @ts-ignore
import { AbsenceDayQueryModel } from '../models';
// @ts-ignore
import { CreateAbsenceDayCommand } from '../models';
// @ts-ignore
import { DayPart } from '../models';
// @ts-ignore
import { ProblemDetails } from '../models';
// @ts-ignore
import { UpdateAbsenceDayCommand } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AbsenceDaysApi - axios parameter creator
 * @export
 */
export const AbsenceDaysApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Creates an Absence Day.
         * @param {CreateAbsenceDayCommand} [createAbsenceDayCommand] The values for an Absence Day.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAbsenceDay: async (createAbsenceDayCommand?: CreateAbsenceDayCommand, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/attendance/absencedays`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true; version=1';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createAbsenceDayCommand,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencedays',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createAbsenceDayCommand, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Deletes an Absence Day.
         * @param {string} id The ID of the Absence Day to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteById: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteById', 'id', id)
            const localVarPath = `/attendance/absencedays/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencedays/{id}',
                httpMethod: 'DELETE'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a single Absence Day based on ID given.
         * @param {string} id Absence Day ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getById', 'id', id)
            const localVarPath = `/attendance/absencedays/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencedays/{id}',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a list of all Absence Days.
         * @param {number} [$top] Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
         * @param {number} [$skip] Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
         * @param {string} [$filter] Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
         * @param {Array<string>} [$select] Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
         * @param {string} [$orderby] Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
         * @param {boolean} [$count] Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList: async ($top?: number, $skip?: number, $filter?: string, $select?: Array<string>, $orderby?: string, $count?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/attendance/absencedays`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)
            if ($top !== undefined) {
                localVarQueryParameter['$top'] = $top;
            }

            if ($skip !== undefined) {
                localVarQueryParameter['$skip'] = $skip;
            }

            if ($filter !== undefined) {
                localVarQueryParameter['$filter'] = $filter;
            }

            if ($select) {
                localVarQueryParameter['$select'] = $select.join(COLLECTION_FORMATS.csv);
            }

            if ($orderby !== undefined) {
                localVarQueryParameter['$orderby'] = $orderby;
            }

            if ($count !== undefined) {
                localVarQueryParameter['$count'] = $count;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencedays',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Updates an Absence Day.
         * @param {string} id The ID of the Absence Day to update.
         * @param {UpdateAbsenceDayCommand} [updateAbsenceDayCommand] The value of an Absence Day.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAbsenceDay: async (id: string, updateAbsenceDayCommand?: UpdateAbsenceDayCommand, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateAbsenceDay', 'id', id)
            const localVarPath = `/attendance/absencedays/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id !== undefined ? id : `-id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "Bearer", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json;odata.metadata=minimal;odata.streaming=true; version=1';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateAbsenceDayCommand,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/attendance/absencedays/{id}',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateAbsenceDayCommand, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AbsenceDaysApi - functional programming interface
 * @export
 */
export const AbsenceDaysApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AbsenceDaysApiAxiosParamCreator(configuration)
    return {
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Creates an Absence Day.
         * @param {AbsenceDaysApiCreateAbsenceDayRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAbsenceDay(requestParameters: AbsenceDaysApiCreateAbsenceDayRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const createAbsenceDayCommand: CreateAbsenceDayCommand = {
                AbsenceId: requestParameters.AbsenceId,
                EmployeeId: requestParameters.EmployeeId,
                Date: requestParameters.Date,
                DurationDays: requestParameters.DurationDays,
                DurationMinutes: requestParameters.DurationMinutes,
                DayPart: requestParameters.DayPart
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAbsenceDay(createAbsenceDayCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Deletes an Absence Day.
         * @param {AbsenceDaysApiDeleteByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteById(requestParameters: AbsenceDaysApiDeleteByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteById(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a single Absence Day based on ID given.
         * @param {AbsenceDaysApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getById(requestParameters: AbsenceDaysApiGetByIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceDayModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getById(requestParameters.id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a list of all Absence Days.
         * @param {AbsenceDaysApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(requestParameters: AbsenceDaysApiGetListRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AbsenceDayQueryModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getList(requestParameters.$top, requestParameters.$skip, requestParameters.$filter, requestParameters.$select, requestParameters.$orderby, requestParameters.$count, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Updates an Absence Day.
         * @param {AbsenceDaysApiUpdateAbsenceDayRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAbsenceDay(requestParameters: AbsenceDaysApiUpdateAbsenceDayRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const updateAbsenceDayCommand: UpdateAbsenceDayCommand = {
                Date: requestParameters.Date,
                DurationDays: requestParameters.DurationDays,
                DurationMinutes: requestParameters.DurationMinutes,
                DayPart: requestParameters.DayPart,
                Id: requestParameters.Id
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAbsenceDay(requestParameters.id, updateAbsenceDayCommand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AbsenceDaysApi - factory interface
 * @export
 */
export const AbsenceDaysApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AbsenceDaysApiFp(configuration)
    return {
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Creates an Absence Day.
         * @param {AbsenceDaysApiCreateAbsenceDayRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAbsenceDay(requestParameters: AbsenceDaysApiCreateAbsenceDayRequest = {}, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.createAbsenceDay(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Deletes an Absence Day.
         * @param {AbsenceDaysApiDeleteByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteById(requestParameters: AbsenceDaysApiDeleteByIdRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a single Absence Day based on ID given.
         * @param {AbsenceDaysApiGetByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getById(requestParameters: AbsenceDaysApiGetByIdRequest, options?: AxiosRequestConfig): AxiosPromise<AbsenceDayModel> {
            return localVarFp.getById(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a list of all Absence Days.
         * @param {AbsenceDaysApiGetListRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList(requestParameters: AbsenceDaysApiGetListRequest = {}, options?: AxiosRequestConfig): AxiosPromise<AbsenceDayQueryModel> {
            return localVarFp.getList(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
         * @summary Updates an Absence Day.
         * @param {AbsenceDaysApiUpdateAbsenceDayRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAbsenceDay(requestParameters: AbsenceDaysApiUpdateAbsenceDayRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateAbsenceDay(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createAbsenceDay operation in AbsenceDaysApi.
 * @export
 * @interface AbsenceDaysApiCreateAbsenceDayRequest
 */
export type AbsenceDaysApiCreateAbsenceDayRequest = {
    
} & CreateAbsenceDayCommand

/**
 * Request parameters for deleteById operation in AbsenceDaysApi.
 * @export
 * @interface AbsenceDaysApiDeleteByIdRequest
 */
export type AbsenceDaysApiDeleteByIdRequest = {
    
    /**
    * The ID of the Absence Day to delete.
    * @type {string}
    * @memberof AbsenceDaysApiDeleteById
    */
    readonly id: string
    
}

/**
 * Request parameters for getById operation in AbsenceDaysApi.
 * @export
 * @interface AbsenceDaysApiGetByIdRequest
 */
export type AbsenceDaysApiGetByIdRequest = {
    
    /**
    * Absence Day ID.
    * @type {string}
    * @memberof AbsenceDaysApiGetById
    */
    readonly id: string
    
}

/**
 * Request parameters for getList operation in AbsenceDaysApi.
 * @export
 * @interface AbsenceDaysApiGetListRequest
 */
export type AbsenceDaysApiGetListRequest = {
    
    /**
    * Show only the first n items, maximum of 250, see [Paging - Top](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptiontop)
    * @type {number}
    * @memberof AbsenceDaysApiGetList
    */
    readonly $top?: number
    
    /**
    * Skip the first n items, see [Paging - Skip](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionskip)
    * @type {number}
    * @memberof AbsenceDaysApiGetList
    */
    readonly $skip?: number
    
    /**
    * Filter items by property values, see [Filtering](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionfilter)
    * @type {string}
    * @memberof AbsenceDaysApiGetList
    */
    readonly $filter?: string
    
    /**
    * Select properties to be returned, see [Select](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect)
    * @type {Array<string>}
    * @memberof AbsenceDaysApiGetList
    */
    readonly $select?: Array<string>
    
    /**
    * Order items by property values, see [Sorting](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionorderby)
    * @type {string}
    * @memberof AbsenceDaysApiGetList
    */
    readonly $orderby?: string
    
    /**
    * Include count of items, see [Count](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptioncount)
    * @type {boolean}
    * @memberof AbsenceDaysApiGetList
    */
    readonly $count?: boolean
    
}

/**
 * Request parameters for updateAbsenceDay operation in AbsenceDaysApi.
 * @export
 * @interface AbsenceDaysApiUpdateAbsenceDayRequest
 */
export type AbsenceDaysApiUpdateAbsenceDayRequest = {
    
    /**
    * The ID of the Absence Day to update.
    * @type {string}
    * @memberof AbsenceDaysApiUpdateAbsenceDay
    */
    readonly id: string
    
} & UpdateAbsenceDayCommand

/**
 * AbsenceDaysApiGenerated - object-oriented interface
 * @export
 * @class AbsenceDaysApiGenerated
 * @extends {BaseAPI}
 */
export class AbsenceDaysApiGenerated extends BaseAPI {
    /**
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
     * @summary Creates an Absence Day.
     * @param {AbsenceDaysApiCreateAbsenceDayRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceDaysApiGenerated
     */
    public createAbsenceDay(requestParameters: AbsenceDaysApiCreateAbsenceDayRequest = {}, options?: AxiosRequestConfig) {
        return AbsenceDaysApiFp(this.configuration).createAbsenceDay(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
     * @summary Deletes an Absence Day.
     * @param {AbsenceDaysApiDeleteByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceDaysApiGenerated
     */
    public deleteById(requestParameters: AbsenceDaysApiDeleteByIdRequest, options?: AxiosRequestConfig) {
        return AbsenceDaysApiFp(this.configuration).deleteById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a single Absence Day based on ID given.
     * @param {AbsenceDaysApiGetByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceDaysApiGenerated
     */
    public getById(requestParameters: AbsenceDaysApiGetByIdRequest, options?: AxiosRequestConfig) {
        return AbsenceDaysApiFp(this.configuration).getById(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a list of all Absence Days.
     * @param {AbsenceDaysApiGetListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceDaysApiGenerated
     */
    public getList(requestParameters: AbsenceDaysApiGetListRequest = {}, options?: AxiosRequestConfig) {
        return AbsenceDaysApiFp(this.configuration).getList(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ![Beta](https://img.shields.io/badge/Status-Beta-yellow) <b>This API request method is currently in beta testing.</b> To gain access to use this method, please contact <a href=\'mailto:hrapi@iris.co.uk\'>hrapi@iris.co.uk.</a>
     * @summary Updates an Absence Day.
     * @param {AbsenceDaysApiUpdateAbsenceDayRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AbsenceDaysApiGenerated
     */
    public updateAbsenceDay(requestParameters: AbsenceDaysApiUpdateAbsenceDayRequest, options?: AxiosRequestConfig) {
        return AbsenceDaysApiFp(this.configuration).updateAbsenceDay(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
