/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An HR Employee\'s Attendance Absence.
 * @export
 * @interface AbsenceModel
 */
export interface AbsenceModel {
    /**
     * The ID of the Employee. <br />  Must exist in the Employees Service. <br />  Cannot be updated once Absence created.
     * @type {string}
     * @memberof AbsenceModel
     */
    'EmployeeId'?: string | null;
    /**
     * The Absence Reason ID. <br />  Must exist in the Attendance Absence Reasons Service. <br />  Cannot be updated once Absence created.
     * @type {string}
     * @memberof AbsenceModel
     */
    'AbsenceReasonId'?: string | null;
    /**
     * The Narrative relating to the Attendance. <br />  Cascade Source: [EmployeeAttendance].[Narrative]
     * @type {string}
     * @memberof AbsenceModel
     */
    'Narrative'?: string | null;
    /**
     * The Start Date of the Attendance. <br />  Cascade Source: [EmployeeAttendance].[StartDate]
     * @type {string}
     * @memberof AbsenceModel
     */
    'StartDate'?: string | null;
    /**
     * The End Date of the Attendance. <br />  Cascade Source: [EmployeeAttendance].[EndDate]  Null if Opened Ended - Cascade Source: [EmployeeAttendance].[OpenEnded]
     * @type {string}
     * @memberof AbsenceModel
     */
    'EndDate'?: string | null;
    /**
     * Source HR System Id. <br />   Cascade Source: [EmployeeAttendance].[RUID] <br />
     * @type {string}
     * @memberof AbsenceModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The date when the Absence was created in the Source HR System. <br />  Cascade Source: [EmployeeAttendance].[SYS_EffectiveDate] <br />
     * @type {string}
     * @memberof AbsenceModel
     */
    'SourceSystemCreatedOn'?: string | null;
    /**
     * The date when the Absence was created or last updated in the Source HR System. <br />  Cascade Source: [EmployeeAttendance].[SYS_ModifiedDate] <br />
     * @type {string}
     * @memberof AbsenceModel
     */
    'SourceSystemLastModifiedOn'?: string | null;
    /**
     * This ID is generated by the Iris HR platform and does not relate to the Cascade ID.
     * @type {string}
     * @memberof AbsenceModel
     */
    'Id'?: string | null;
    /**
     * The date when the Absence was created in the Iris HR platform.
     * @type {string}
     * @memberof AbsenceModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users.
     * @type {string}
     * @memberof AbsenceModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date when the Absence was created or last updated.
     * @type {string}
     * @memberof AbsenceModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users.
     * @type {string}
     * @memberof AbsenceModel
     */
    'LastModifiedBy'?: string | null;
}

