/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceReasonModel } from './absence-reason-model';

/**
 * 
 * @export
 * @interface AbsenceReasonQueryModel
 */
export interface AbsenceReasonQueryModel {
    /**
     * 
     * @type {string}
     * @memberof AbsenceReasonQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AbsenceReasonQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AbsenceReasonQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<AbsenceReasonModel>}
     * @memberof AbsenceReasonQueryModel
     */
    'Value'?: Array<AbsenceReasonModel> | null;
}

