/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DayPart } from './day-part';

/**
 * An Attendance Absence Day
 * @export
 * @interface AbsenceDayModel
 */
export interface AbsenceDayModel {
    /**
     * The ID of the parent Absence. <br />  Must exist in the Attendance Absence Service.
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'AbsenceId'?: string | null;
    /**
     * The ID of the Employee. <br />  Must exist in the Employees Service.
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'EmployeeId'?: string | null;
    /**
     * The date of the Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[StartDate]
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'Date'?: string;
    /**
     * The duration in days for this Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[DurationDays]
     * @type {number}
     * @memberof AbsenceDayModel
     */
    'DurationDays'?: number;
    /**
     * The duration in minutes for this Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[Duration]
     * @type {number}
     * @memberof AbsenceDayModel
     */
    'DurationMinutes'?: number | null;
    /**
     * The parts of days.
     * @type {DayPart}
     * @memberof AbsenceDayModel
     */
    'DayPart'?: DayPart;
    /**
     * Source HR System Id. <br />  Cascade Source: [EmployeeAttendanceDates].[Sequence] <br />  Read Only
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The ID of the Absence Day. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'Id'?: string | null;
    /**
     * The date time when the Absence Day was created in the Iris HR platform.
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date time when the Absence Day was created or last updated.
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDayModel
     */
    'LastModifiedBy'?: string | null;
}

