/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AbsenceModel } from './absence-model';

/**
 * 
 * @export
 * @interface AbsenceQueryModel
 */
export interface AbsenceQueryModel {
    /**
     * 
     * @type {string}
     * @memberof AbsenceQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AbsenceQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AbsenceQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<Array<AbsenceModel>>}
     * @memberof AbsenceQueryModel
     */
    'Value'?: Array<Array<AbsenceModel>> | null;
}

