/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Ownership } from './ownership';

/**
 * The Address of a property
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * The Owner of the entity
     * @type {Ownership}
     * @memberof Address
     */
    'Ownership'?: Ownership;
    /**
     * Address Line 1 <br />  Cascade Source: [EmployeeHomeAddress].[Address1]
     * @type {string}
     * @memberof Address
     */
    'Address1'?: string | null;
    /**
     * Address Line 2 <br />  Cascade Source: [EmployeeHomeAddress].[Address2]
     * @type {string}
     * @memberof Address
     */
    'Address2'?: string | null;
    /**
     * Address Line 3 <br />  Cascade Source: [EmployeeHomeAddress].[Address3]
     * @type {string}
     * @memberof Address
     */
    'Address3'?: string | null;
    /**
     * Address Line 4 <br />  Cascade Source: [EmployeeHomeAddress].[Address4]
     * @type {string}
     * @memberof Address
     */
    'Address4'?: string | null;
    /**
     * Address Line 5 <br />  Cascade Source: [EmployeeHomeAddress].[Address5]
     * @type {string}
     * @memberof Address
     */
    'Address5'?: string | null;
    /**
     * Address UK Post Code <br />  Cascade Source: [EmployeeHomeAddress].[Postcode]
     * @type {string}
     * @memberof Address
     */
    'PostCode'?: string | null;
}

