/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Bank Address
 * @export
 * @interface BankAddress
 */
export interface BankAddress {
    /**
     * The first line of Bank Address <br />  Cascade Source: [EmployeeBank].[Address1]
     * @type {string}
     * @memberof BankAddress
     */
    'Address1'?: string | null;
    /**
     * The second line of Bank Address <br />  Cascade Source: [EmployeeBank].[Address2]
     * @type {string}
     * @memberof BankAddress
     */
    'Address2'?: string | null;
    /**
     * The third line of Bank Address <br />  Cascade Source: [EmployeeBank].[Address3]
     * @type {string}
     * @memberof BankAddress
     */
    'Address3'?: string | null;
    /**
     * The fourth line of Bank Address <br />  Cascade Source: [EmployeeBank].[Address4]
     * @type {string}
     * @memberof BankAddress
     */
    'Address4'?: string | null;
    /**
     * Post Code of the Bank <br />  Cascade Source: [EmployeeBank].[Postcode]
     * @type {string}
     * @memberof BankAddress
     */
    'PostCode'?: string | null;
}

