/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankDetailsModel } from './bank-details-model';

/**
 * 
 * @export
 * @interface BankDetailsQueryModel
 */
export interface BankDetailsQueryModel {
    /**
     * 
     * @type {string}
     * @memberof BankDetailsQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BankDetailsQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BankDetailsQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<BankDetailsModel>}
     * @memberof BankDetailsQueryModel
     */
    'Value'?: Array<BankDetailsModel> | null;
}

