/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankAddress } from './bank-address';

/**
 * An HR Employee\'s Bank Details.
 * @export
 * @interface BankDetailsModel
 */
export interface BankDetailsModel {
    /**
     * The ID of the HR Employee. <br />  Must exist in the Employee Service.
     * @type {string}
     * @memberof BankDetailsModel
     */
    'EmployeeId'?: string | null;
    /**
     * Bank Name. <br />  Cascade Source: [EmployeeBank].[BankName]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'BankName'?: string | null;
    /**
     * 
     * @type {BankAddress}
     * @memberof BankDetailsModel
     */
    'BankAddress'?: BankAddress;
    /**
     * Account Name. <br />  Cascade Source: [EmployeeBank].[AccountName]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'AccountName'?: string | null;
    /**
     * Account Number. <br />  Cascade Source: [EmployeeBank].[AccountNumber]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'AccountNumber'?: string | null;
    /**
     * Sort Code. <br />  Cascade Source: [EmployeeBank].[SortCode]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'SortCode'?: string | null;
    /**
     * Roll Number. <br />  Cascade Source: [EmployeeBank].[RollNumber]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'RollNumber'?: string | null;
    /**
     * The Internal ID for the source HR Product. <br />  Cascade Source: [EmployeeBank].[RUID]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The date when the Bank details record was created in the Source HR System. <br />  Cascade Source: [EmployeeBank].[SYS_EffectiveDate]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'SourceSystemCreatedOn'?: string | null;
    /**
     * The latest date when the Bank details record was created or last updated in the Source HR System. <br />  Cascade Source: Latest of [EmployeeBank].[SYS_ModifiedDate]
     * @type {string}
     * @memberof BankDetailsModel
     */
    'SourceSystemLastModifiedOn'?: string | null;
    /**
     * The ID of Bank Details. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
     * @type {string}
     * @memberof BankDetailsModel
     */
    'Id'?: string | null;
    /**
     * The date time when the Bank Details was created in the Iris HR platform.
     * @type {string}
     * @memberof BankDetailsModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof BankDetailsModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date time when the Bank Details was created or last updated.
     * @type {string}
     * @memberof BankDetailsModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof BankDetailsModel
     */
    'LastModifiedBy'?: string | null;
}

