/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An HR Employee\'s Benefits.
 * @export
 * @interface BenefitModel
 */
export interface BenefitModel {
    /**
     * The EmployeeId. <br />  Cascade Source: [EmployeeBenefits].[EmployeeId]
     * @type {string}
     * @memberof BenefitModel
     */
    'EmployeeId'?: string | null;
    /**
     * The Type. <br />  Cascade Source: [EmployeeBenefits].[Code]
     * @type {string}
     * @memberof BenefitModel
     */
    'Type'?: string | null;
    /**
     * The Description. <br />  Cascade Source: [EmployeeBenefits].[Notes]
     * @type {string}
     * @memberof BenefitModel
     */
    'Description'?: string | null;
    /**
     * The Value. <br />  Cascade Source: [EmployeeBenefits].[Value]
     * @type {number}
     * @memberof BenefitModel
     */
    'Value'?: number | null;
    /**
     * The Start Date. <br />  Cascade Source: [EmployeeBenefits].[StartDate]
     * @type {string}
     * @memberof BenefitModel
     */
    'StartDate'?: string | null;
    /**
     * The End Date. <br />  Cascade Source: [EmployeeBenefits].[EndDate]
     * @type {string}
     * @memberof BenefitModel
     */
    'EndDate'?: string | null;
    /**
     * The P11DValue. <br />  Cascade Source: [EmployeeBenefits].[P11DValueCurrency]
     * @type {number}
     * @memberof BenefitModel
     */
    'P11DValue'?: number | null;
    /**
     * The Suspended value. <br />  Cascade Source: [EmployeeBenefits].[Suspended]
     * @type {boolean}
     * @memberof BenefitModel
     */
    'Suspended'?: boolean;
    /**
     * The ID of the Benefit. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
     * @type {string}
     * @memberof BenefitModel
     */
    'Id'?: string | null;
    /**
     * Source HR System Id. <br />  Cascade Source: [EmployeeBenefits].[Ruid] <br />  Read Only
     * @type {string}
     * @memberof BenefitModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The date time when the Benefit was created in the Iris HR platform.
     * @type {string}
     * @memberof BenefitModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof BenefitModel
     */
    'CreatedBy'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof BenefitModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof BenefitModel
     */
    'LastModifiedBy'?: string | null;
}

