/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateAbsenceCommand
 */
export interface CreateAbsenceCommand {
    /**
     * The ID of the Employee. <br />  Must exist in the Employees Service. <br />  Cannot be updated once Absence created.
     * @type {string}
     * @memberof CreateAbsenceCommand
     */
    'EmployeeId'?: string | null;
    /**
     * The Absence Reason ID. <br />  Must exist in the Attendance Absence Reasons Service. <br />  Cannot be updated once Absence created.
     * @type {string}
     * @memberof CreateAbsenceCommand
     */
    'AbsenceReasonId'?: string | null;
    /**
     * The Narrative relating to the Attendance. <br />  Cascade Source: [EmployeeAttendance].[Narrative]
     * @type {string}
     * @memberof CreateAbsenceCommand
     */
    'Narrative'?: string | null;
    /**
     * The Start Date of the Attendance. <br />  Cascade Source: [EmployeeAttendance].[StartDate]
     * @type {string}
     * @memberof CreateAbsenceCommand
     */
    'StartDate'?: string | null;
    /**
     * The End Date of the Attendance. <br />  Cascade Source: [EmployeeAttendance].[EndDate]  Null if Opened Ended - Cascade Source: [EmployeeAttendance].[OpenEnded]
     * @type {string}
     * @memberof CreateAbsenceCommand
     */
    'EndDate'?: string | null;
}

