/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankAddress } from './bank-address';

/**
 * 
 * @export
 * @interface CreateBankDetailsCommand
 */
export interface CreateBankDetailsCommand {
    /**
     * The ID of the HR Employee. <br />  Must exist in the Employee Service.
     * @type {string}
     * @memberof CreateBankDetailsCommand
     */
    'EmployeeId'?: string | null;
    /**
     * Bank Name. <br />  Cascade Source: [EmployeeBank].[BankName]
     * @type {string}
     * @memberof CreateBankDetailsCommand
     */
    'BankName'?: string | null;
    /**
     * 
     * @type {BankAddress}
     * @memberof CreateBankDetailsCommand
     */
    'BankAddress'?: BankAddress;
    /**
     * Account Name. <br />  Cascade Source: [EmployeeBank].[AccountName]
     * @type {string}
     * @memberof CreateBankDetailsCommand
     */
    'AccountName'?: string | null;
    /**
     * Account Number. <br />  Cascade Source: [EmployeeBank].[AccountNumber]
     * @type {string}
     * @memberof CreateBankDetailsCommand
     */
    'AccountNumber'?: string | null;
    /**
     * Sort Code. <br />  Cascade Source: [EmployeeBank].[SortCode]
     * @type {string}
     * @memberof CreateBankDetailsCommand
     */
    'SortCode'?: string | null;
    /**
     * Roll Number. <br />  Cascade Source: [EmployeeBank].[RollNumber]
     * @type {string}
     * @memberof CreateBankDetailsCommand
     */
    'RollNumber'?: string | null;
}

