/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DayPart } from './day-part';

/**
 * 
 * @export
 * @interface CreateAbsenceDayCommand
 */
export interface CreateAbsenceDayCommand {
    /**
     * The ID of the parent Absence. <br />  Must exist in the Attendance Absence Service.
     * @type {string}
     * @memberof CreateAbsenceDayCommand
     */
    'AbsenceId'?: string | null;
    /**
     * The ID of the Employee. <br />  Must exist in the Employees Service.
     * @type {string}
     * @memberof CreateAbsenceDayCommand
     */
    'EmployeeId'?: string | null;
    /**
     * The date of the Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[StartDate]
     * @type {string}
     * @memberof CreateAbsenceDayCommand
     */
    'Date'?: string;
    /**
     * The duration in days for this Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[DurationDays]
     * @type {number}
     * @memberof CreateAbsenceDayCommand
     */
    'DurationDays'?: number;
    /**
     * The duration in minutes for this Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[Duration]
     * @type {number}
     * @memberof CreateAbsenceDayCommand
     */
    'DurationMinutes'?: number | null;
    /**
     * The parts of days.
     * @type {DayPart}
     * @memberof CreateAbsenceDayCommand
     */
    'DayPart'?: DayPart;
}

