/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The parts of days.
 * @export
 * @enum {string}
 */
export type DayPart = 'AM' | 'PM' | 'AllDay' | 'None'

