/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Ownership } from './ownership';

/**
 * An Email with Ownership.
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * The Owner of the entity
     * @type {Ownership}
     * @memberof Email
     */
    'Ownership'?: Ownership;
    /**
     * The Email Address. <br />  Cascade Source: <br />  Ownership = Organization then [Employee].[WorkEmail], Maximum Length: 320<br />  Ownership = Personal then [EmployeeHomeAddress].[HomeEmail], Maximum Length: 50.
     * @type {string}
     * @memberof Email
     */
    'Value'?: string | null;
}

