/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeModel } from './employee-model';

/**
 * 
 * @export
 * @interface EmployeeQueryModel
 */
export interface EmployeeQueryModel {
    /**
     * 
     * @type {string}
     * @memberof EmployeeQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EmployeeQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EmployeeQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<EmployeeModel>}
     * @memberof EmployeeQueryModel
     */
    'Value'?: Array<EmployeeModel> | null;
}

