/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeAbsenceReasonModel
 */
export interface EmployeeAbsenceReasonModel {
    /**
     * The Parent ID of this Absence Reason. <br />  Cascade Source: [ValidAttendanceTypes].[Key].
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'EmployeeId'?: string | null;
    /**
     * The Name of this Absence Reason. <br />  Cascade Source: <br />  [ValidAttendanceCategory].[Category] when ParentID is null; <br />  [ValidAttendanceTypes].[Type] when ParentID is not null.
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'AbsenceReasonId'?: string | null;
    /**
     * The Absence Reason For The Employee should be recorded in Days or not.
     * @type {boolean}
     * @memberof EmployeeAbsenceReasonModel
     */
    'ShowInDays'?: boolean;
    /**
     * The ID of the Employee Absence Reason.
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'Id'?: string | null;
    /**
     * The date time when the Employee Absence Reason was created in the Iris HR platform.
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date time when the Employee Absence Reason was created or last updated.
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof EmployeeAbsenceReasonModel
     */
    'LastModifiedBy'?: string | null;
}

