/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EntitlementModel } from './entitlement-model';

/**
 * 
 * @export
 * @interface EntitlementQueryModel
 */
export interface EntitlementQueryModel {
    /**
     * 
     * @type {string}
     * @memberof EntitlementQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EntitlementQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof EntitlementQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<EntitlementModel>}
     * @memberof EntitlementQueryModel
     */
    'Value'?: Array<EntitlementModel> | null;
}

