/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An Employee\'s Attendance Entitlement.
 * @export
 * @interface EntitlementModel
 */
export interface EntitlementModel {
    /**
     * The ID of the HR Employee. <br />  Must exist in the Employee Service.
     * @type {string}
     * @memberof EntitlementModel
     */
    'EmployeeId'?: string | null;
    /**
     * The Absence Reason ID. <br />  Must exist in the Absence Reason Service.
     * @type {string}
     * @memberof EntitlementModel
     */
    'AbsenceReasonId'?: string | null;
    /**
     * The Entitlement Year Name. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[EntitlementYearName]
     * @type {string}
     * @memberof EntitlementModel
     */
    'EntitlementYearName'?: string | null;
    /**
     * The status of Open indicates whether the entitlement is active. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[Open]
     * @type {boolean}
     * @memberof EntitlementModel
     */
    'Open'?: boolean;
    /**
     * The Start Date of this Entitlement. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[StartDate]
     * @type {string}
     * @memberof EntitlementModel
     */
    'StartDate'?: string;
    /**
     * The End Date of this Entitlement. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[EndDate]
     * @type {string}
     * @memberof EntitlementModel
     */
    'EndDate'?: string;
    /**
     * The optional description of this Entitlement. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[Narrative]
     * @type {string}
     * @memberof EntitlementModel
     */
    'Narrative'?: string | null;
    /**
     * The number of Base Entitlement Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[BaseEntitlementDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'BaseDays'?: number;
    /**
     * The number of Base Entitlement Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[BaseEntitlement]
     * @type {number}
     * @memberof EntitlementModel
     */
    'BaseMinutes'?: number | null;
    /**
     * The number of Carry Days allowed. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[CarryDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'CarryDays'?: number;
    /**
     * The number of Carry Minutes allowed. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[Carry]
     * @type {number}
     * @memberof EntitlementModel
     */
    'CarryMinutes'?: number | null;
    /**
     * The date when Carry Days should be used by. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[CarryUsebyDays]
     * @type {string}
     * @memberof EntitlementModel
     */
    'CarryUseByDate'?: string | null;
    /**
     * The number of Carry Days lost. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[CarryLostDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'CarryLostDays'?: number | null;
    /**
     * The number of Carry Minutes lost. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[CarryLost]
     * @type {number}
     * @memberof EntitlementModel
     */
    'CarryLostMinutes'?: number | null;
    /**
     * The number of Manual Adjustment Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[ManualAdjustmentDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'ManualAdjustmentDays'?: number;
    /**
     * The number of Manual Adjustment Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[ManualAdjustment]
     * @type {number}
     * @memberof EntitlementModel
     */
    'ManualAdjustmentMinutes'?: number | null;
    /**
     * The number of Adjustment Days due to service length. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[ServiceLengthAdjustmentDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'ServiceLengthAdjustmentDays'?: number;
    /**
     * The number of Adjustment Minutes due to service length. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[ServiceLengthAdjustment]
     * @type {number}
     * @memberof EntitlementModel
     */
    'ServiceLengthAdjustmentMinutes'?: number | null;
    /**
     * The number of New Starter Adjustment Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[NewStarterAdjustmentDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'NewStarterAdjustmentDays'?: number;
    /**
     * The number of New Starter Adjustment Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[NewStarterAdjustment]
     * @type {number}
     * @memberof EntitlementModel
     */
    'NewStarterAdjustmentMinutes'?: number | null;
    /**
     * [Obsolete] The number of Leaver Adjustment Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[LeaverAdjustmentDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'LeaverAdjusmentDays'?: number;
    /**
     * [Obsolete] The number of Leaver Adjustment Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[LeaverAdjustment]
     * @type {number}
     * @memberof EntitlementModel
     */
    'LeaverAdjusmentMinutes'?: number | null;
    /**
     * The number of Leaver Adjustment Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[LeaverAdjustmentDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'LeaverAdjustmentDays'?: number | null;
    /**
     * The number of Leaver Adjustment Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[LeaverAdjustment]
     * @type {number}
     * @memberof EntitlementModel
     */
    'LeaverAdjustmentMinutes'?: number | null;
    /**
     * The number of Part Time Adjustment Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[PTProrataDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'PartTimeAdjustmentDays'?: number;
    /**
     * The number of Part Time Adjustment Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[PTProrata]
     * @type {number}
     * @memberof EntitlementModel
     */
    'PartTimeAdjustmentMinutes'?: number | null;
    /**
     * The number of Bank Holiday Adjustment Day. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[BHProrataDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'BankHolidayAdjustmentDays'?: number;
    /**
     * The number of Bank Holiday Adjustment Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[BHProrata]
     * @type {number}
     * @memberof EntitlementModel
     */
    'BankHolidayAdjustmentMinutes'?: number | null;
    /**
     * The number of Buy Sell Days. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[BuySellDays]
     * @type {number}
     * @memberof EntitlementModel
     */
    'BuySellDays'?: number;
    /**
     * The number of Buy Sell Minutes. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[BuySell]
     * @type {number}
     * @memberof EntitlementModel
     */
    'BuySellMinutes'?: number | null;
    /**
     * The total Entitlement in days. <br />  = BaseDays <br />      + ServiceLengthAdjustmentDays <br />      + NewStarterAdjustmentDays <br />      + ManualAdjustmentDays <br />      + CarryDays <br />      + PartTimeAdjustmentDays <br />      + BankHolidayAdjustmentDays <br />      + BuySellDays <br />      - CarryLostDays <br />      + LeaverAdjustmentDays
     * @type {number}
     * @memberof EntitlementModel
     */
    'TotalEntitlementDays'?: number | null;
    /**
     * The total Entitlement in minutes. <br />  = BaseMinutes <br />      + ServiceLengthAdjustmentMinutes <br />      + NewStarterAdjustmentMinutes <br />      + ManualAdjustmentMinutes <br />      + CarryMinutes <br />      + PartTimeAdjustmentMinutes <br />      + BankHolidayAdjustmentMinutes <br />      + BuySellMinutes <br />      - CarryLostMinutes <br />      + LeaverAdjustmentMinutes
     * @type {number}
     * @memberof EntitlementModel
     */
    'TotalEntitlementMinutes'?: number | null;
    /**
     * The Internal ID of the Source HR Product. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[Key]
     * @type {string}
     * @memberof EntitlementModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The date when the Entitlement record was created in the Source HR System. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[SYS_EffectiveDate]
     * @type {string}
     * @memberof EntitlementModel
     */
    'SourceSystemCreatedOn'?: string | null;
    /**
     * The date when the Entitlement record was created or last updated in the Source HR System. <br />  Cascade Source: [EmployeeAttendanceEntitlementYear].[SYS_ModifiedDate]
     * @type {string}
     * @memberof EntitlementModel
     */
    'SourceSystemLastModifiedOn'?: string | null;
    /**
     * This ID is generated by the Iris HR platform and does not relate to the Cascade Employee Entitlement ID.
     * @type {string}
     * @memberof EntitlementModel
     */
    'Id'?: string | null;
    /**
     * The date when the Entitlement was created in the Iris HR platform.
     * @type {string}
     * @memberof EntitlementModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof EntitlementModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date when the Entitlement was created or last updated.
     * @type {string}
     * @memberof EntitlementModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof EntitlementModel
     */
    'LastModifiedBy'?: string | null;
}

