/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Hierarchy node.
 * @export
 * @interface HierarchyNodeModel
 */
export interface HierarchyNodeModel {
    /**
     * The Parent ID of this Hierarchy node. <br />  Must exist in the Hierarchy Service.
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'ParentId'?: string | null;
    /**
     * The Level of the Hierarchy node. <br />  Cascade Source: [ValidHierarchyX].[level]
     * @type {number}
     * @memberof HierarchyNodeModel
     */
    'Level'?: number;
    /**
     * The Title of this Hierarchy node. <br />  Cascade Source: [ValidHierarchyX].[name]
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'Title'?: string | null;
    /**
     * Hierarchy node is disabled. <br />  Cascade Source: [ValidHierarchyX].[disabled]
     * @type {boolean}
     * @memberof HierarchyNodeModel
     */
    'Disabled'?: boolean;
    /**
     * Source HR System Id. <br />  Cascade Source: [ValidHierarchyX].[HierarchyNode] <br />  Read Only
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The date when the Hierarchy node record was created in the Source HR System. <br />  Cascade Source: [ValidHierarchyX].[createdon]
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'SourceSystemCreatedOn'?: string | null;
    /**
     * The date when the Hierarchy node record was created or last updated in the Source HR System. <br />  Cascade Source: [ValidHierarchyX].[disabledon] if exists else [ValidHierachyX].[createdon]
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'SourceSystemLastModifiedOn'?: string | null;
    /**
     * This ID of the Hierarchy node. <br />  This field is generated by Iris HR platform and not related to the Cascade ID.
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'Id'?: string | null;
    /**
     * The date time when the Hierarchy node was created in the Iris HR platform.
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date time when the Hierarchy node was created or last updated.
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users at the moment.
     * @type {string}
     * @memberof HierarchyNodeModel
     */
    'LastModifiedBy'?: string | null;
}

