/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HierarchyNodeModel } from './hierarchy-node-model';

/**
 * 
 * @export
 * @interface HierarchyNodeQueryModel
 */
export interface HierarchyNodeQueryModel {
    /**
     * 
     * @type {string}
     * @memberof HierarchyNodeQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof HierarchyNodeQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof HierarchyNodeQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<HierarchyNodeModel>}
     * @memberof HierarchyNodeQueryModel
     */
    'Value'?: Array<HierarchyNodeModel> | null;
}

