/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobModel } from './job-model';

/**
 * 
 * @export
 * @interface JobQueryModel
 */
export interface JobQueryModel {
    /**
     * 
     * @type {string}
     * @memberof JobQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JobQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<JobModel>}
     * @memberof JobQueryModel
     */
    'Value'?: Array<JobModel> | null;
}

