/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An HR Employee\'s Job.
 * @export
 * @interface JobModel
 */
export interface JobModel {
    /**
     * The title of the Job. <br />  Cascade Source: [EmployeeJobs].[JobTitle]
     * @type {string}
     * @memberof JobModel
     */
    'JobTitle'?: string | null;
    /**
     * The classification of the Job e.g. Technical, Professional, Managerial. <br />  Cascade Source: [EmployeeJobs].[Classification] translated through the JOBCLASSIFICATION system list.
     * @type {string}
     * @memberof JobModel
     */
    'Classification'?: string | null;
    /**
     * The start date of the Job. <br />  Required. <br />  Cascade Source: [EmployeeJobs].[SYS_EffectiveDate]
     * @type {string}
     * @memberof JobModel
     */
    'StartDate'?: string;
    /**
     * The end date of the Job. <br />  Automatically Calculated. <br />  Cascade Source: [EmployeeJobs].[SYS_CalculatedEndDate]
     * @type {string}
     * @memberof JobModel
     */
    'EndDate'?: string | null;
    /**
     * The name of the working calendar of the Job. <br />  Cascade Source: [EmployeeJobs].[CalendarName] which comes from [ValidWorkingCalendar].[CalendarName]
     * @type {string}
     * @memberof JobModel
     */
    'WorkingCalendar'?: string | null;
    /**
     * The ID of the Employee that is the line manager for this Job. <br />  Must exist in Employees Service. <br />  Cascade Source: [EmployeeJobs].[WorksForEmployeeId]
     * @type {string}
     * @memberof JobModel
     */
    'LineManagerId'?: string | null;
    /**
     * The ID of the Employee\'s Hierarchy node of the Job. <br />  Must exist in Hierarchy Service.
     * @type {string}
     * @memberof JobModel
     */
    'HierarchyNodeId'?: string | null;
    /**
     * The Job is currently active. <br />  Automatically Calculated. <br />  Cascade Source: [EmployeeJobs].[sys_ActiveJob]
     * @type {boolean}
     * @memberof JobModel
     */
    'Active'?: boolean;
    /**
     * The salary of the Job. <br />  Cascade Source: [EmployeeJobs].[BasicPay]
     * @type {number}
     * @memberof JobModel
     */
    'Salary'?: number | null;
    /**
     * The ID of the Employee of the Job. <br />  Must exist in Employee Service.
     * @type {string}
     * @memberof JobModel
     */
    'EmployeeId'?: string | null;
    /**
     * The contract of the Job e.g. Full Time, Part Time. <br />  Cascade Source: [EmployeeJobs].[ContractType] translated through the EMPLOYMENTTYPES system list.
     * @type {string}
     * @memberof JobModel
     */
    'Contract'?: string | null;
    /**
     * How often the Job\'s salary will be paid e.g. Monthly, Weekly. <br />  Cascade Source: [EmployeeJobs].[PayFrequency] translated through the PAY FREQ system list.
     * @type {string}
     * @memberof JobModel
     */
    'PayFrequency'?: string | null;
    /**
     * The unit of measurement the salary is specified against e.g. Yearly, Hourly. <br />  Cascade Source: [EmployeeJobs].[PayBasis] translated through the PAY BASIS system list.
     * @type {string}
     * @memberof JobModel
     */
    'PayBasis'?: string | null;
    /**
     * The full-time equivalent to a full time employee\'s hours e.g. 1 = Full Time, 0.5 = Half Hours. <br />  Cascade Source: [EmployeeJobs].[FTE].
     * @type {number}
     * @memberof JobModel
     */
    'FullTimeEquivalent'?: number | null;
    /**
     * The readonly property of employee position. <br />  Cascade Source: [EmployeeJobs].[Postid].
     * @type {string}
     * @memberof JobModel
     */
    'Position'?: string | null;
    /**
     * The reason for the change. <br />  Cascade Source: [EmployeeJobs].[Reason].
     * @type {string}
     * @memberof JobModel
     */
    'ChangeReason'?: string | null;
    /**
     * The readonly property of public holiday. <br />  Cascade Soruce: [EmployeeJobs].[HolidayLocation].
     * @type {string}
     * @memberof JobModel
     */
    'PublicHoliday'?: string | null;
    /**
     * The readonly property of pay grade.  <br />  Cascade Source: [EmployeeJobs].[PayGrade].
     * @type {string}
     * @memberof JobModel
     */
    'PayGrade'?: string | null;
    /**
     * The readonly property of pay spinal point. <br />  Cascade Source: [EmployeeJobs].[SpinalPoint].
     * @type {number}
     * @memberof JobModel
     */
    'SpinalPoint'?: number | null;
    /**
     * The next increment date.  <br />  Cascade Source: [EmployeeJobs].[IncrementDate].
     * @type {string}
     * @memberof JobModel
     */
    'NextIncrementDate'?: string | null;
    /**
     * The timesheet location. <br />  Cascade Source: [EmployeeJobs].[TimesheetLocation].
     * @type {string}
     * @memberof JobModel
     */
    'TimesheetLocation'?: string | null;
    /**
     * The readonly property of time sheet rule set. <br />  Cascade Source: [EmployeeJobs].[TimesheetRuleSetID].
     * @type {string}
     * @memberof JobModel
     */
    'TimesheetRuleSet'?: string | null;
    /**
     * The time set lunch duration. <br />  Cascade Source: [EmployeeJobs].[LunchDuration].
     * @type {string}
     * @memberof JobModel
     */
    'TimesheetLunchDuration'?: string | null;
    /**
     * The readonly property of automatic enrolment profiles. <br />  Cascade Source: [EmployeeJobs].[AutoEnrolmentProfile].
     * @type {string}
     * @memberof JobModel
     */
    'AutoEnrolmentProfile'?: string | null;
    /**
     * The expense submission frequency. <br />  Cascade Source: [EmployeeJobs].[ExpenseSubmissionFrequency].
     * @type {string}
     * @memberof JobModel
     */
    'ExpenseSubmissionFrequency'?: string | null;
    /**
     * The cost centre. <br />  Cascade Source: [EmployeeJobs].[CostCentre].
     * @type {string}
     * @memberof JobModel
     */
    'CostCentre'?: string | null;
    /**
     * The job family. <br />  Cascade Source: [EmployeeJobs].[JobFamily].
     * @type {string}
     * @memberof JobModel
     */
    'JobFamily'?: string | null;
    /**
     * The flag to indicate if the employee is an apprentice under 25. <br />  Cascade Source: [EmployeeJobs].[ApprenticeUnder25].
     * @type {boolean}
     * @memberof JobModel
     */
    'ApprenticeUnder25'?: boolean | null;
    /**
     * The end date of the apprenticeship. <br />  Cascade Source: [EmployeeJobs].[ApprenticeshipEndDate].
     * @type {string}
     * @memberof JobModel
     */
    'ApprenticeshipEndDate'?: string | null;
    /**
     * The end date of the contract. <br />  Cascade Source: [EmployeeJobs].[ContractEndDate].
     * @type {string}
     * @memberof JobModel
     */
    'ContractEndDate'?: string | null;
    /**
     * The readonly property of reports to post. <br />  Cascade Source: [EmployeeJobs].[ReportsToPost].
     * @type {string}
     * @memberof JobModel
     */
    'ReportsToPost'?: string | null;
    /**
     * Normal hours. <br />  Cascade Source: [EmployeeJobs].[NormalHours].
     * @type {number}
     * @memberof JobModel
     */
    'NormalHours'?: number | null;
    /**
     * The real time information of irregular frequency. <br />  Cascade Source: [EmployeeJobs].[RTIIrregularFrequency].
     * @type {string}
     * @memberof JobModel
     */
    'RealTimeInformationIrregularFrequency'?: string | null;
    /**
     * The notice period. <br />  Cascade Source: [EmployeeJobs].[NoticePeriod].
     * @type {string}
     * @memberof JobModel
     */
    'NoticePeriod'?: string | null;
    /**
     * This ID is generated by the Iris Hr platform and does not relate to the Cascade ID.
     * @type {string}
     * @memberof JobModel
     */
    'Id'?: string | null;
    /**
     * Source HR System Id. <br />  Cascade Source: [EmployeeJobs].[Ruid] <br />  Read Only
     * @type {string}
     * @memberof JobModel
     */
    'SourceSystemId'?: string | null;
    /**
     * The date when the Job was created in the Iris Hr platform.
     * @type {string}
     * @memberof JobModel
     */
    'CreatedOn'?: string;
    /**
     * The date when the Job was created in the Source HR System. <br />  Cascade Source: [EmployeeJobs].[SYS_EffectiveDate] <br />  Note: In Cascade this value is also the Start Date of the Job and can changed at any time. <br />  Read Only
     * @type {string}
     * @memberof JobModel
     */
    'SourceSystemCreatedOn'?: string | null;
    /**
     * Not used as the Iris Hr platform has no concept of users at the moment.
     * @type {string}
     * @memberof JobModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date when the Job was created or last updated.
     * @type {string}
     * @memberof JobModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * The date when the Job was created or last updated in the Source HR System. <br />  Cascade Source: [EmployeeJobs].[SYS_ModifiedDate] <br />  Read Only
     * @type {string}
     * @memberof JobModel
     */
    'SourceSystemLastModifiedOn'?: string | null;
    /**
     * Not used as Iris Hr platform has no concept of users at the moment.
     * @type {string}
     * @memberof JobModel
     */
    'LastModifiedBy'?: string | null;
}

