/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Ownership } from './ownership';
import { PhoneType } from './phone-type';

/**
 * A Phone Number with Ownership and Type properties
 * @export
 * @interface Phone
 */
export interface Phone {
    /**
     * The Owner of the entity
     * @type {Ownership}
     * @memberof Phone
     */
    'Ownership'?: Ownership;
    /**
     * The Type of Phone
     * @type {PhoneType}
     * @memberof Phone
     */
    'Type'?: PhoneType;
    /**
     * The Phone Number value. <br />  Cascade Source:  <br />  Ownership = Organization, Type = Landline Then [Employee].[WorkPhone] <br />  Ownership = Organization, Type = Mobile Then [Employee].[WorkMobilePhoneNumber] <br />  Ownership = Personal, Type = Landline Then [EmployeeHomeAddress].[Phone] <br />  Ownership = Personal, Type = Mobile Then [EmployeeHomeAddress].[MobilePhone]
     * @type {string}
     * @memberof Phone
     */
    'Value'?: string | null;
}

