/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicHolidayModel } from './public-holiday-model';

/**
 * 
 * @export
 * @interface PublicHolidayQueryModel
 */
export interface PublicHolidayQueryModel {
    /**
     * 
     * @type {string}
     * @memberof PublicHolidayQueryModel
     */
    'ODataContext'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PublicHolidayQueryModel
     */
    'ODataCount'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PublicHolidayQueryModel
     */
    'ODataNextLink'?: string | null;
    /**
     * 
     * @type {Array<PublicHolidayModel>}
     * @memberof PublicHolidayQueryModel
     */
    'Value'?: Array<PublicHolidayModel> | null;
}

