/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PublicHolidayDay
 */
export interface PublicHolidayDay {
    /**
     * The description of the Public Holiday Day. <br />  Cascade Source: [ValidBankHolidays].[Description]
     * @type {string}
     * @memberof PublicHolidayDay
     */
    'Description'?: string | null;
    /**
     * The date of the Public Holiday Day. <br />  Cascade Source: [ValidBankHolidays].[Date]
     * @type {string}
     * @memberof PublicHolidayDay
     */
    'Date'?: string;
    /**
     * Source HR System Id. <br />  Cascade Source: [ValidBankHolidays].[key] <br />  Read Only
     * @type {string}
     * @memberof PublicHolidayDay
     */
    'SourceSystemId'?: string | null;
}

