/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicHolidayDay } from './public-holiday-day';

/**
 * 
 * @export
 * @interface PublicHolidayModel
 */
export interface PublicHolidayModel {
    /**
     * The description of the Public Holiday. <br />  This is usually the location of the Public Holiday. <br />  Cascade Source: [ValidBankHolidays].[HolidayLocation]
     * @type {string}
     * @memberof PublicHolidayModel
     */
    'Description'?: string | null;
    /**
     * A list of Public Holiday Days.
     * @type {Array<PublicHolidayDay>}
     * @memberof PublicHolidayModel
     */
    'Days'?: Array<PublicHolidayDay> | null;
    /**
     * This ID is generated by the Iris Hr platform and does not relate to the Cascade ID.
     * @type {string}
     * @memberof PublicHolidayModel
     */
    'Id'?: string | null;
    /**
     * The date when the Public Holiday was created in the Iris HR platform.
     * @type {string}
     * @memberof PublicHolidayModel
     */
    'CreatedOn'?: string;
    /**
     * Not used as the Iris HR platform has no concept of users.
     * @type {string}
     * @memberof PublicHolidayModel
     */
    'CreatedBy'?: string | null;
    /**
     * The date when the Public Holiday was created or last updated.
     * @type {string}
     * @memberof PublicHolidayModel
     */
    'LastModifiedOn'?: string | null;
    /**
     * Not used as the Iris HR platform has no concept of users.
     * @type {string}
     * @memberof PublicHolidayModel
     */
    'LastModifiedBy'?: string | null;
}

