/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DayPart } from './day-part';

/**
 * 
 * @export
 * @interface UpdateAbsenceDayCommand
 */
export interface UpdateAbsenceDayCommand {
    /**
     * The date of the Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[StartDate]
     * @type {string}
     * @memberof UpdateAbsenceDayCommand
     */
    'Date'?: string;
    /**
     * The duration in days for this Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[DurationDays]
     * @type {number}
     * @memberof UpdateAbsenceDayCommand
     */
    'DurationDays'?: number;
    /**
     * The duration in minutes for this Absence Day. <br />  Cascade Source: [EmployeeAttendanceDates].[Duration]
     * @type {number}
     * @memberof UpdateAbsenceDayCommand
     */
    'DurationMinutes'?: number | null;
    /**
     * The parts of days.
     * @type {DayPart}
     * @memberof UpdateAbsenceDayCommand
     */
    'DayPart'?: DayPart;
    /**
     * The ID of the Absence Day. <br />  Must exist in the Attendance Absence Day Service.
     * @type {string}
     * @memberof UpdateAbsenceDayCommand
     */
    'Id'?: string | null;
}

