/*
HR API

<a href='swaggerv2.json'>Download Swagger Json in OAS2 Format.</a>

The version of the OpenAPI document: 2
Contact: hrapi@iris.co.uk

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Email } from './email';
import { Phone } from './phone';

/**
 * 
 * @export
 * @interface UpdateEmployeeCommand
 */
export interface UpdateEmployeeCommand {
    /**
     * The Display ID of the Employee. <br />  If provided must be unqiue, If null then it will automatically be generated. <br />  Cascade Source: [Employee].[DisplayEmployeeId]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'DisplayId'?: string | null;
    /**
     * The Title of the Employee. E.g. Mr, Mrs, Miss. <br />  Cascade Source: [Employee].[Title] translated through the TITLE system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'TitleHonorific'?: string | null;
    /**
     * The First Name of the Employee. <br />  Required. <br />  Cascade Source: [Employee].[Forename]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'FirstName'?: string | null;
    /**
     * The name the Employee is commonly known as. <br />  Cascade Source: [Employee].[KnownAs]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'KnownAs'?: string | null;
    /**
     * Any other name that the Employee has. <br />  Cascade Source: [Employee].[OtherName]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'OtherName'?: string | null;
    /**
     * The Last Name, Surname or Family Name of the Employee. <br />  Required. <br />  Cascade Source: [Employee].[Surname]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'LastName'?: string | null;
    /**
     * The Cost Centre assigned to the Employee. <br />  Cascade Source: [Employee].[CostCentre]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'CostCentre'?: string | null;
    /**
     * The Status of the Employee E.g. On Holiday, Sick. <br />  Automatically Calculated. <br />  Cascade Source: [Sysview_Employee_Status].[StatusDescription]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'WorkingStatus'?: string | null;
    /**
     * Indicates if the Employee is a Manager. <br />  True if any other Employee\'s active <see cref=\"T:Iris.Api.Hr.Employee.Domain.Entities.V1.Job\">Job</see> has this Employee as their Line Manager. <br />  Automaticaly Calculated.
     * @type {boolean}
     * @memberof UpdateEmployeeCommand
     */
    'IsManager'?: boolean | null;
    /**
     * The National Insurance Number of the Employee. <br />  Cascade Source: [Employee].[NationalInsuranceNo]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'NationalInsuranceNumber'?: string | null;
    /**
     * The Payroll ID of the Employee. <br />  Cascade Source: [Employee].[PayrollId]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'PayrollId'?: string | null;
    /**
     * The Tax Code of the Employee. <br />  Cascade Source: [Employee].[TaxCode]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'TaxCode'?: string | null;
    /**
     * Indicates if the Employee should be included in Payroll. <br />  Cascade Source: [Employee].[IncludeInPayroll]
     * @type {boolean}
     * @memberof UpdateEmployeeCommand
     */
    'IncludeInPayroll'?: boolean | null;
    /**
     * The date the Employee started with their current Employer. <br />  Cascade Source: [Employee].[EmployeeStartDate]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'EmploymentStartDate'?: string | null;
    /**
     * The date the Employee left their current Employer. <br />  Cascade Source: [Employee].[EmployementLeftDate]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'EmploymentLeftDate'?: string | null;
    /**
     * The date the Employee\'s continuous service should be applied from. <br />  Cascade Source: [Employee].[ContServiceDate]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'ContinuousServiceDate'?: string | null;
    /**
     * The Date of Birth of the Employee. <br />  Cascade Source: [Employee].[DateOfBirth]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'DateOfBirth'?: string | null;
    /**
     * The date of the last working date of the Employee. <br />  Cascade Source: [Employee].[LeaverLastWorkDate]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'LastWorkingDate'?: string | null;
    /**
     * The Gender of the Employee. <br />  Cascade Source: [Employee].[Sex] translated through the GENDER system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'Gender'?: string | null;
    /**
     * The Ethnicity of the Employee. <br />  Cascade Source: [Employee].[EthnicOrigin] translated through the ETHNICTORIGIN system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'Ethnicity'?: string | null;
    /**
     * The Nationality of the Employee. <br />  Cascade Source: [Employee].[Nationality] translated through the NATIONALITY system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'Nationality'?: string | null;
    /**
     * The Religion of the Employee. <br />  Cascade Source: [Employee].[Religion] transalated through the RELIGION system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'Religion'?: string | null;
    /**
     * The reason for the Employee to Leave. <br />  Cascade Source: [Employee].[LeaverReason]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'LeaverReason'?: string | null;
    /**
     * The marrital status of the Employee. <br />  Cascade Source: [Employee.[MaritalStatus] translated through the MARITALSTATUS system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'MaritalStatus'?: string | null;
    /**
     * The <see cref=\"T:Iris.Api.Hr.Employee.Domain.Entities.V1.Phone\">Phone Numbers</see> belonging to the Employee.
     * @type {Array<Phone>}
     * @memberof UpdateEmployeeCommand
     */
    'Phones'?: Array<Phone> | null;
    /**
     * The <see cref=\"T:Iris.Api.Hr.Employee.Domain.Entities.V1.Email\">Email Addresses</see> belonging to the Employee.
     * @type {Array<Email>}
     * @memberof UpdateEmployeeCommand
     */
    'Emails'?: Array<Email> | null;
    /**
     * The <see cref=\"T:Iris.Api.Hr.Employee.Domain.Entities.V1.Address\">Addresses</see> belonging to the Employee.
     * @type {Array<Address>}
     * @memberof UpdateEmployeeCommand
     */
    'Addresses'?: Array<Address> | null;
    /**
     * The Gender Identity of the Employee. <br />  Cascade Source: [Employee].[GenderIdentity] translated through the GenderIdentity system list.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'GenderIdentity'?: string | null;
    /**
     * The Windows Username of the Employee. <br />  Cascade Source: [Employee].[WindowsUsername]
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'WindowsUsername'?: string | null;
    /**
     * The ID of the Employee. <br />  Must exist in the Employee Service.
     * @type {string}
     * @memberof UpdateEmployeeCommand
     */
    'Id'?: string | null;
}

